name: Bump and Tag Version Workflow

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  bump-tag-version:
    name: Bump and Tag Version
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
          allowed-endpoints: |
            tech.jfheinrich.eu:443

      - id: setup-secrets
        name: Setup secrets
        uses: jfheinrich-eu/psono-secret-whisperer@b42169213e4392bdd2f1d5a7be76bfeb8c246074 # v1.1.0
        with:
          ci_api_key_id: ${{ secrets.PSONO_API_KEY_ID }}
          ci_api_secret_key_hex: ${{ secrets.PSONO_API_SECRET_KEY_HEX }}
          ci_server_url: ${{ vars.PSONO_SERVER_URL }}
          secret_id: ${{ secrets.PSONO_GITHUB_CLI_TOKEN }}
          secret_type: "secret"
          secret_fields: "password"
          mask_secrets: "password"

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: jefflinse/pr-semver-bump@6b735b474f354e20438496d978e2a80953073d74 # v1.7.3
        name: Bump and Tag Version
        with:
          mode: bump
          repo-token: ${{ steps.setup-secrets.outputs.secret1 }}
          major-label: major release
          minor-label: minor release
          patch-label: patch release
          noop-labels: |
            documentation change
            skip-release
            dependencies
          require-release-notes: true
          release-notes-prefix: "<!--- START AUTOGENERATED NOTES --->"
          release-notes-suffix: "<!--- END AUTOGENERATED NOTES --->"
          with-v: true
          base-branch: false
