name: New release Workflow
permissions:
  contents: write
  pull-requests: write

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Match semantic versioning tags like v1.0.0, v2.3.4, etc.'

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit
          allowed-endpoints: |
            api.github.com:443
            uploads.github.com:443
            objects.githubusercontent.com:443
            raw.githubusercontent.com:443

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.12"

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@6d71e098526ee17bae963f058d34cd763378337f # v1.10.2
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Update README action reference
        run: |
          pip install --upgrade pip
          python .github/scripts/update_readme_action_reference.py

      - name: Create Release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: |
            ## Changes
            ${{ steps.changelog.outputs.changes }}

      - name: Check if auto-commit and push is needed
        id: check-auto-commit-push
        run: |
          set -e
          CHANGED_FILES="$(git add --dry-run .)"
          if [[ -z "$CHANGED_FILES" ]]; then
            echo "No changes to commit."
            echo "auto-commit-push=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected, proceeding with commit and push."
            echo "auto-commit-push=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        id: cpr
        if: steps.check-auto-commit-push.outputs.auto-commit-push == 'true'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e #v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "docs: Update CHANGELOG.md and README.md for ${{ github.ref_name }}"
          body: "Automated change log and readme update for release.\n\nThis PR updates the CHANGELOG.md and README.md files with the latest changes from the release.\n\nChanges:\n${{ steps.changelog.outputs.changes }}"
          base: main
          branch: changelog-update-${{ github.run_id }}
          commit-message: "docs: update CHANGELOG.md and README.md for ${{ github.ref_name }} [skip ci]"
          labels: documentation, skip-release
          delete-branch: true

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        continue-on-error: true
        uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d # v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge
