name: Create new release
permissions:
  contents: write
  pull-requests: write

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Match semantic versioning tags like v1.0.0, v2.3.4, etc.'

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@6d71e098526ee17bae963f058d34cd763378337f # v1.10.2
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          includeInvalidCommits: true

      - name: Write changelog changes to file
        id: changelog-changes
        env:
          CHANGELOG: ${{ steps.changelog.outputs.changes }}
        run: echo "${CHANGELOG}" >> CHANGELOG-changes.md

      - name: Create Release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body_path: CHANGELOG-changes.md

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
        with:
          branch: main
          commit_message: "docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]"
          file_pattern: CHANGELOG.md
